const VIEWS={dashboard:['总览','系统总览与运行状态'],collection:['数据采集','资源池接口采集'],database:['系统数据库','已有系统名录与基准管理'],matching:['名称匹配','名称匹配待确认'],excel:['Excel 生成','统计结果输出'],validation:['数据校验','接口数据异常检查'],logs:['运行日志','任务与文件中心'],settings:['系统设置','服务器参数']};
const ICONS={dashboard:'⌂',collection:'↻',database:'▣',matching:'⌘',excel:'▤',validation:'✓',logs:'≡',settings:'⚙'};let boot=null,currentJob=null,jobTimer=null,searchTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,opt={}){let r=await fetch(url,opt);let ct=r.headers.get('content-type')||'';let data=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error(data?.error||data||`HTTP ${r.status}`);return data}
function toast(msg,type='ok'){let e=document.createElement('div');e.className='toast '+type;e.textContent=msg;$('#toastHost').appendChild(e);setTimeout(()=>e.remove(),4200)}
function gotoView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent=VIEWS[name][0];$('#pageEyebrow').textContent=VIEWS[name][1]+' · Web v2.0.1';if(name==='database')searchSystems();if(name==='logs'){loadLogs();loadFiles()}if(name==='excel'){refreshExcelPools();loadFiles()}if(name==='matching'||name==='validation')syncDetailDates();window.scrollTo({top:0,behavior:'smooth'})}
function renderNav(){let n=$('#nav');n.innerHTML=Object.entries(VIEWS).map(([k,v],i)=>`<button data-view="${k}" class="nav-btn ${i===0?'active':''}" onclick="gotoView('${k}')"><span class="nav-icon">${ICONS[k]}</span>${v[0]}</button>`).join('')}
async function refreshAll(){try{boot=await api('/api/bootstrap');renderBoot();await refreshResults();toast('数据已刷新')}catch(e){toast(e.message,'err');$('#serverState').textContent='连接异常'}}
function setPoolOptions(){let html=boot.pools.map(p=>`<option>${esc(p.name)}</option>`).join('');['collectPool','scanPool','matchPool','validationPool'].forEach(id=>$('#'+id).innerHTML=html)}
function setDates(){let d=boot.default_dates;['dashStart','collectStart','matchStart','excelStart','validationStart'].forEach(id=>{if(!$('#'+id).value)$('#'+id).value=d.start});['dashEnd','collectEnd','matchEnd','excelEnd','validationEnd'].forEach(id=>{if(!$('#'+id).value)$('#'+id).value=d.end})}
function renderBoot(){let d=boot.database,b=boot.baseline_pools.length;$('#miniBaseline').textContent=`${b} / 6`;$('#heroBaseline').textContent=`${b}/6`;$('#miniDbState').textContent=b===6?'基准完成':'待建立';$('#miniDbState').className='badge '+(b===6?'ok':'warn');$('#statSystems').textContent=d.total;$('#statActive').textContent=d.active;$('#statNew').textContent=d.unack_new;$('#statAudit').textContent=`${d.audit_passed}/6`;$('#dbTotal').textContent=d.total;$('#dbActive').textContent=d.active;$('#dbBaseline').textContent=`${b}/6`;$('#dbAudit').textContent=`${d.audit_passed}/6`;setPoolOptions();setDates();let aud=boot.audit_statuses||{};$('#poolCards').innerHTML=boot.pools.map(p=>{let base=boot.baseline_pools.includes(p.name),a=aud[p.name];let state=a?(a.passed?'已校对通过':'校对有差异'):(base?'基准已建立':'未建立基准');return `<div class="pool-item"><div><strong>${esc(p.name)}</strong><span class="badge ${base?'ok':'warn'}">${base?'BASE':'NEW'}</span></div><div class="state">${esc(state)}</div><small>${p.kind==='front'?'getEdsDetail / getInterfaceDetail':'政务外网平台接口'}</small></div>`}).join('');renderEvents(boot.events||[]);$('#serverInfo').innerHTML=[['版本','v'+boot.app.version],['服务器时间',boot.app.server_time],['监听地址',`${boot.app.host}:${boot.app.port}`],['数据库',`${d.total} 个系统`]].map(x=>`<div class="info-row"><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('');let s=boot.settings;$('#setHost').value=s.host;$('#setPort').value=s.port;$('#setTimeout').value=s.request_timeout;$('#setTemplate').value=s.template_path}
function renderEvents(items){$('#eventList').innerHTML=items.length?items.map(e=>`<div class="event-item"><div><strong>${esc(e.application_name)}</strong><small>${esc(e.pool)} · ${esc(e.detected_at)}${e.detail?' · '+esc(e.detail):''}</small></div><span class="event-type">${esc(e.event_type)}</span></div>`).join(''):'<div class="muted">当前没有未确认的系统变化。</div>'}
function syncDatesFromDashboard(){['collectStart','excelStart','matchStart','validationStart'].forEach(id=>$('#'+id).value=$('#dashStart').value);['collectEnd','excelEnd','matchEnd','validationEnd'].forEach(id=>$('#'+id).value=$('#dashEnd').value)}
function syncDetailDates(){['matchStart','validationStart'].forEach(id=>$('#'+id).value=$('#collectStart').value||$('#dashStart').value);['matchEnd','validationEnd'].forEach(id=>$('#'+id).value=$('#collectEnd').value||$('#dashEnd').value)}
async function startJob(url,body){try{let r=await api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});currentJob=r.job_id;showJob();clearInterval(jobTimer);jobTimer=setInterval(showJob,1000);toast('任务已提交')}catch(e){toast(e.message,'err')}}
async function showJob(){if(!currentJob)return;try{let j=await api('/api/jobs/'+currentJob);let text=`任务：${j.kind}\n状态：${j.status}\n开始：${j.started_at||'-'}\n\n${(j.progress||[]).join('\n')}`;if(j.error)text+=`\n\n错误：${j.error}`;if(j.status==='success'&&j.result)text+=`\n\n完成结果：\n${JSON.stringify(j.result,null,2)}`;$('#jobBox').className='job-box';$('#jobBox').textContent=text;if(['success','failed'].includes(j.status)){clearInterval(jobTimer);if(j.status==='success'){toast(`${j.kind}完成`);await refreshAll();if(j.kind==='生成Excel'&&j.result?.download){let a=document.createElement('a');a.href=j.result.download;a.textContent='下载刚生成的 Excel';a.className='primary-btn';$('#jobBox').appendChild(document.createElement('br'));$('#jobBox').appendChild(a)}}else toast(j.error||'任务失败','err')}}catch(e){clearInterval(jobTimer);toast(e.message,'err')}}
function runTest(){startJob('/api/test',{pool:$('#collectPool').value,start:$('#collectStart').value,end:$('#collectEnd').value,token:$('#collectToken').value})}
function runCollect(){startJob('/api/collect',{pool:$('#collectPool').value,start:$('#collectStart').value,end:$('#collectEnd').value,token:$('#collectToken').value})}
async function refreshResults(){if(!boot)return;let s=$('#collectStart').value||boot.default_dates.start,e=$('#collectEnd').value||boot.default_dates.end;try{let r=await api(`/api/results?start=${encodeURIComponent(s)}&end=${encodeURIComponent(e)}`);$('#resultCards').innerHTML=r.items.length?r.items.map(x=>`<div class="result-item"><div><strong>${esc(x.pool)}</strong><small>${x.rows} 行标准结果</small></div><span class="badge ok">已采集</span></div>`).join(''):'<div class="muted">当前统计周期还没有已采集结果。</div>'}catch(err){$('#resultCards').innerHTML=`<div class="muted">${esc(err.message)}</div>`}}
async function scanDatabase(audit){startJob(audit?'/api/audit':'/api/scan',{pool:$('#scanPool').value,start:$('#collectStart').value||$('#dashStart').value,end:$('#collectEnd').value||$('#dashEnd').value})}
async function searchSystems(){try{let q=$('#systemQuery')?.value||'';let r=await api('/api/systems?q='+encodeURIComponent(q));$('#systemsBody').innerHTML=r.items.length?r.items.map(x=>`<tr><td>${esc(x.pool)}</td><td>${esc(x.application_name)}</td><td>${esc(x.customer_name)}</td><td>${esc(x.app_id)}</td><td>${esc(x.status)}</td><td>${esc(x.first_seen)}</td><td>${esc(x.last_seen)}</td></tr>`).join(''):'<tr><td colspan="7">没有匹配记录</td></tr>'}catch(e){toast(e.message,'err')}}
function debouncedSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(searchSystems,260)}
async function ackEvents(){try{await api('/api/events/ack',{method:'POST'});await refreshAll();toast('已确认当前事件')}catch(e){toast(e.message,'err')}}
async function uploadDb(input){let f=input.files[0];if(!f)return;if(!confirm('导入基准库前会自动备份当前 systems.db。继续吗？'))return;try{let r=await fetch('/api/database/import',{method:'POST',headers:{'X-Filename':encodeURIComponent(f.name)},body:f});let data=await r.json();if(!r.ok)throw new Error(data.error||'导入失败');toast(`数据库导入成功：${data.result.system_count} 个系统`);await refreshAll();searchSystems()}catch(e){toast(e.message,'err')}finally{input.value=''}}
async function uploadGov(){let f=$('#govImportFile').files[0];if(!f)return toast('请选择 XLSX 文件','err');let pool=$('#govImportPool').value,s=$('#collectStart').value,e=$('#collectEnd').value;try{let r=await fetch(`/api/government/import?pool=${encodeURIComponent(pool)}&start=${s}&end=${e}`,{method:'POST',headers:{'X-Filename':encodeURIComponent(f.name)},body:f});let d=await r.json();if(!r.ok)throw new Error(d.error||'导入失败');toast(`${pool} 导入成功：${d.rows} 行`);refreshResults()}catch(err){toast(err.message,'err')}}
async function loadResultDetails(mode){let pool=$('#'+(mode==='matching'?'matchPool':'validationPool')).value,s=$('#'+(mode==='matching'?'matchStart':'validationStart')).value,e=$('#'+(mode==='matching'?'matchEnd':'validationEnd')).value;try{let r=await api(`/api/result?pool=${encodeURIComponent(pool)}&start=${s}&end=${e}`);if(mode==='matching')$('#matchBody').innerHTML=r.match_issues.length?r.match_issues.map(x=>`<tr><td>${esc(x.first_name)}</td><td>${esc(x.second_name)}</td><td>${esc(x.candidates)}</td><td>${esc(x.status)}</td><td>${esc(x.reason)}</td><td>${esc(x.suggestion)}</td></tr>`).join(''):'<tr><td colspan="6">没有名称匹配待确认记录</td></tr>';else $('#validationBody').innerHTML=r.validation_issues.length?r.validation_issues.map(x=>`<tr><td>${esc(x.source)}</td><td>${esc(x.application_name)}</td><td>${esc(x.issue_type)}</td><td>${esc(x.detail)}</td></tr>`).join(''):'<tr><td colspan="4">没有数据校验异常</td></tr>'}catch(err){toast(err.message,'err')}}
async function refreshExcelPools(){let s=$('#excelStart').value||$('#collectStart').value,e=$('#excelEnd').value||$('#collectEnd').value;if(!s||!e)return;try{let r=await api(`/api/results?start=${s}&end=${e}`);let got=new Map(r.items.map(x=>[x.pool,x]));$('#excelPools').innerHTML=boot.pools.map(p=>{let x=got.get(p.name);return `<label class="check-item"><input type="checkbox" value="${esc(p.name)}" ${x?'':'disabled'} ${x?'checked':''}><span>${esc(p.name)}<small>${x?x.rows+' 行':'未采集'}</small></span></label>`}).join('');loadFiles()}catch(err){toast(err.message,'err')}}
async function generateExcel(){let pools=$$('#excelPools input:checked').map(x=>x.value);startJob('/api/excel',{start:$('#excelStart').value,end:$('#excelEnd').value,pools})}
async function loadLogs(){try{let r=await api('/api/logs');$('#logBox').textContent=r.lines.join('\n')||'暂无日志'}catch(e){$('#logBox').textContent=e.message}}
async function loadFiles(){try{let r=await api('/api/files');let render=r.items.filter(x=>x.kind==='Excel').slice(0,30);$('#excelFiles').innerHTML=render.length?render.map(fileHtml).join(''):'<div class="muted">还没有 Excel 输出文件。</div>';$('#fileList').innerHTML=r.items.slice(0,80).map(fileHtml).join('')}catch(e){toast(e.message,'err')}}
function fileHtml(x){return `<div class="file-item"><div><strong>${esc(x.name)}</strong><small>${esc(x.kind)} · ${esc(x.modified)} · ${(x.size/1024).toFixed(1)} KB</small></div><a class="glass-btn small" href="/download?path=${encodeURIComponent(x.path)}">下载</a></div>`}
async function saveSettings(){try{let r=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({host:$('#setHost').value,port:+$('#setPort').value,request_timeout:+$('#setTimeout').value,template_path:$('#setTemplate').value})});boot.settings=r.settings;toast('设置已保存')}catch(e){toast(e.message,'err')}}
renderNav();refreshAll();